### PR TITLE
Errors, documentation for errors and updated examples

### LINKED ISSUE #24: Subclass errors
Currently, `Error` is thrown when something goes wrong. We should start using subclasses of `Error` like `TypeError` etc.

### PR DESCRIPTION
**Pull request by harshjv**
Fixes #24 

- [x] Subclass errors
- [x] Add documentation for errors and methods
- [x] Update examples
- [x] Update readme
- [x] Update tests

### CODE REVIEW

File: src/errors.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+import BaseError from 'standard-error'
```
Comment (monokh) [inline src/errors.js:1]: I didn't notice `standard-error` being added to `package.json` i think i found it part of `babel/core`. Is it good practice to rely on transitive dependencies or better to add it as a direct dependency of the project? Just wondering

File: src/index.js [hunk 2]
```diff
@@ -5,42 +5,47 @@ import * as Ajv from 'ajv'
...
 
 export default class ChainAbstractionLayer {
   /**
    * ChainAbstractionLayer client
-   * @param {object} [provider] - The provider instance.
-   * @param {string} [version] - Version string
+   * @param {string} [version] - Minimum blockchain node version to support
    */
-  constructor (provider, version) {
+  constructor (version) {
```
Comment (monokh) [inline src/index.js]: Is the version used? do we need to keep it?

**Review by monokh — CHANGES_REQUESTED** [review]
LGTM, just some small questions

File: src/errors.js (hunk 1 above)
Comment (harshjv) [reply src/errors.js:1]: `standard-error` was already in our `package.json`. I was earlier using it for `RpcError`.

File: src/index.js (hunk 2 above)
Comment (harshjv) [reply src/index.js]: Adding a provider directly in constructor has very limited use cases because one single provider cannot do all the tasks. Should we keep the old version?

File: src/errors.js (hunk 1 above)
Comment (monokh) [reply src/errors.js:1]: sure is 👍  cool

File: src/index.js (hunk 2 above)
Comment (monokh) [reply src/index.js]: I see your point about the provider and i agree, but I'm asking about the `version` 😄

Comment (monokh) [reply src/index.js]: I guess nothing to do with this PR actually so i'm happy to address that later

**Review by monokh — APPROVED** [review]

File: src/index.js (hunk 2 above)
Comment (harshjv) [reply src/index.js]: Oh. Yes, `version` is used. See https://github.com/ConsenSys/chainabstractionlayer/blob/master/src/index.js#L70-L74

File: examples/node/bitcoin/ledger.js [hunk 3]
```diff
@@ -3,10 +3,9 @@ const { BitcoinLedgerProvider } = ChainAbstractionLayer.providers.bitcoin
 
 const prettyPrintJson = (val) => console.log(JSON.stringify(val, null, 2))
 
-const bitcoinLedgerProvider = new BitcoinLedgerProvider('http://localhost:8080', 'bitcoin', 'local321')
-const bitcoin = new ChainAbstractionLayer(bitcoinLedgerProvider)
+const bitcoin = new ChainAbstractionLayer()
+bitcoin.addProvider(new BitcoinLedgerProvider())
```
Comment (matthewjablack) [inline examples/node/bitcoin/ledger.js:7]: Is there a reason for removing ability to add providers through constructor. I see that there is more consistency in adding providers rather than initializing and then adding providers (since most users will be adding multiple providers), but should we still provide option to add provider through constructor?

Comment (harshjv) [reply examples/node/bitcoin/ledger.js:7]: We can do that too. I removed it because, in all of our examples, we are using multiple providers. For now, let's keep it. We will discuss this again if something comes up.

**Review by matthewjablack — APPROVED** [review]
Thanks for that small change @harshjv 

LGTM 🎉
